package com.ruskserver.moveearth_addtional.analytics;

import com.ruskserver.moveearth_addtional.analytics.config.AnalyticsConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

import static org.junit.jupiter.api.Assertions.*;

public class AnalyticsConfigTest {

    @TempDir
    Path tempConfigDir;

    @BeforeEach
    public void setUp() {
        AnalyticsConfig.resetToDefaults();
    }

    @AfterEach
    public void tearDown() {
        AnalyticsConfig.resetToDefaults();
    }

    @Test
    public void testAutoGenerateDefaultConfig() {
        Path configFile = tempConfigDir.resolve(AnalyticsConfig.CONFIG_FILE_NAME);
        assertFalse(Files.exists(configFile));

        AnalyticsConfig.loadConfig(tempConfigDir);

        assertTrue(Files.exists(configFile), "設定ファイルが存在しない場合はデフォルトで自動生成されるべき");
        assertTrue(AnalyticsConfig.isDedicatedServerOnly());
        assertTrue(AnalyticsConfig.isWebServerEnabled());
        assertEquals("127.0.0.1", AnalyticsConfig.getWebServerHost());
        assertEquals(8080, AnalyticsConfig.getWebServerPort());
        assertTrue(AnalyticsConfig.isWebServerRequireAuth());
    }

    @Test
    public void testLoadCustomConfig() throws Exception {
        Path configFile = tempConfigDir.resolve(AnalyticsConfig.CONFIG_FILE_NAME);
        Properties props = new Properties();
        props.setProperty("dedicated_server_only", "false");
        props.setProperty("web_server_enabled", "true");
        props.setProperty("web_server_host", "0.0.0.0");
        props.setProperty("web_server_port", "9090");
        props.setProperty("web_server_require_auth", "false");

        try (OutputStream out = Files.newOutputStream(configFile)) {
            props.store(out, "Test Config");
        }

        AnalyticsConfig.loadConfig(tempConfigDir);

        assertFalse(AnalyticsConfig.isDedicatedServerOnly());
        assertTrue(AnalyticsConfig.isWebServerEnabled());
        assertEquals("0.0.0.0", AnalyticsConfig.getWebServerHost());
        assertEquals(9090, AnalyticsConfig.getWebServerPort());
        assertFalse(AnalyticsConfig.isWebServerRequireAuth());
    }

    @Test
    public void testSaveAndReloadConfig() {
        AnalyticsConfig.setDedicatedServerOnly(false);
        AnalyticsConfig.setWebServerHost("192.168.1.100");
        AnalyticsConfig.setWebServerPort(8888);
        AnalyticsConfig.setWebServerRequireAuth(true);

        AnalyticsConfig.saveConfig(tempConfigDir);

        // 一旦リセット
        AnalyticsConfig.resetToDefaults();
        assertEquals(8080, AnalyticsConfig.getWebServerPort());

        // 再ロード
        AnalyticsConfig.loadConfig(tempConfigDir);
        assertFalse(AnalyticsConfig.isDedicatedServerOnly());
        assertEquals("192.168.1.100", AnalyticsConfig.getWebServerHost());
        assertEquals(8888, AnalyticsConfig.getWebServerPort());
    }

    @Test
    public void testInvalidPortFallback() throws Exception {
        Path configFile = tempConfigDir.resolve(AnalyticsConfig.CONFIG_FILE_NAME);
        Properties props = new Properties();
        props.setProperty("web_server_port", "invalid_port");

        try (OutputStream out = Files.newOutputStream(configFile)) {
            props.store(out, "Test Config");
        }

        AnalyticsConfig.loadConfig(tempConfigDir);
        assertEquals(8080, AnalyticsConfig.getWebServerPort(), "無効なポート指定時はデフォルトの8080にフォールバックするべき");
    }
}
